# Generated by Django 4.1.1 on 2023-04-13 18:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('water', '0002_alter_waterintake_intake'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='many_journal_entries', to='user.enduser')),
            ],
        ),
        migrations.AddField(
            model_name='enduser',
            name='journal_entries',
            field=models.ManyToManyField(to='user.journalentry'),
        ),
        migrations.AddField(
            model_name='enduser',
            name='water_drank_in_oz',
            field=models.ManyToManyField(to='water.waterintake'),
        ),
    ]
